### ISSUE TITLE
Logo and menu aren't even

### ISSUE THREAD

**Issue by barkerd427** [DevOpsKC/devopskc#6]
An update has put the menu below the logo on the desktop version.

**Comment by slickplaid** [comment]
This starts at between the 991px width and ends at 768px responsive breakpoint.

A couple of options:

1. Reduce the font size of the menu items;    
1. **Reduce the padding between menu items**
1. Reduce the padding of the icon

Reducing the padding between menu items is probably the easiest, although it goes against some design guidelines for top menus and touch elements.


```css
@media (min-width: 768px)
.navbar-nav>li>a { 
  padding: 15px 10px 18px 10px; 
}
```

Overrides bootstrap's `navbar-nav` class, so unless you namespace it, it could clobber other menus (if any exist which they don't currently).

Creating a pull request now.
